apiVersion: v1
data:
  .kube-event-logger.yaml: |
    namespace: "" # empty string for all namespaces
    resource:
      pod: true
      deployment: true
      configMap: false
      ingress: true
      job: false
      namespace: false
      persistentVolume: false
      replicaSet: false
      replicationController: false
      secret: false
      service: true

kind: ConfigMap
metadata:
  name: kube-event-logger
  namespace: kube-system
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kube-event-logger
rules:
- apiGroups: ["", "extensions", "apps"]
  resources: ["pods", "deployments", "deployments", "services", "ingresses"]
  verbs: ["get", "watch", "list"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-event-logger
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: kube-event-logger
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kube-event-logger
subjects:
  - kind: ServiceAccount
    name: kube-event-logger
    namespace: kube-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-event-logger
  namespace: kube-system
  labels:
    app: kube-event-logger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kube-event-logger
  template:
    metadata:
      labels:
        app: kube-event-logger
    spec:
      containers:
      - name: kube-event-logger
        image: kube-system/kube-event-logger:latest
        resources:
          requests:
            memory: "5Mi"
            cpu: "100m"
          limits:
            memory: "50Mi"
            cpu: "200m"
        volumeMounts:
        - name: config-volume
          mountPath: /.kube-event-logger.yaml
          subPath: .kube-event-logger.yaml
      volumes:
        - name: config-volume
          configMap:
            name: kube-event-logger
      restartPolicy: Always
      serviceAccountName: kube-event-logger
