kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kube-event-logger
rules:
- apiGroups: [""]
  resources: ["pods", "replicationcontrollers"]
  verbs: ["get", "watch", "list"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-event-logger
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: kube-event-logger
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kube-event-logger
subjects:
  - kind: ServiceAccount
    name: kube-event-logger
    namespace: kube-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-event-logger
  namespace: kube-system
  labels:
    app: kube-event-logger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kube-event-logger
  template:
    metadata:
      labels:
        app: kube-event-logger
    spec:
      containers:
      - name: kube-event-logger
        image: marcusnoble/kube-event-logger:latest
        resources:
          requests:
            memory: "5Mi"
            cpu: "100m"
          limits:
            memory: "50Mi"
            cpu: "200m"
      restartPolicy: Always
      serviceAccountName: kube-event-logger
